apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-user-service
  labels:
    app: loyalty-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-user-service
  template:
    metadata:
      labels:
        app: loyalty-user-service
    spec:
      containers:
      - name: loyalty-user-service
        image: user
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 9080
        envFrom:
        - secretRef:
            name: loyalty-db-secret
        - secretRef:
            name: loyalty-oidc-secret
        env:
        - name: EVENT_SERVICE_URL
          value: "http://loyalty-event-service:9080/loyalty/v1/events"
        - name: WLP_LOGGING_CONSOLE_LOGLEVEL
          value: INFO
---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-user-service
  labels:
    app: loyalty-user-service
spec:
  ports:
  - port: 9080
    targetPort: 9080
  selector:
    app: loyalty-user-service
---
apiVersion: v1
kind: Route
metadata:
  name: loyalty-user-service
spec:
  to:
    kind: Service
    name: loyalty-user-service

