apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-transaction-service
  labels:
    app: loyalty-transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-transaction-service
  template:
    metadata:
      labels:
        app: loyalty-transaction-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: loyalty-transaction-service
        image: anthonyamanse/transaction-service:with-auth-1.1
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 9080
        envFrom:
        - secretRef:
            name: loyalty-db-secret
        - secretRef:
            name: loyalty-oidc-secret
        env:
        - name: USER_SERVICE_URL
          value: "http://loyalty-user-service:9080/loyalty/v1/users"
        - name: KNATIVE_SERVICE_URL
          value: "http://process-transaction.example-loyalty.svc.cluster.local"
        - name: WLP_LOGGING_CONSOLE_LOGLEVEL
          value: INFO
---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-transaction-service
  labels:
    app: loyalty-transaction-service
spec:
  ports:
  - port: 9080
    targetPort: 9080
  selector:
    app: loyalty-transaction-service
