apiVersion: batch/v1
kind: Job
metadata:
  name: cc-schema-load
  labels:
    app: cc-schema-load
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: cc-schema-load
          image: ykoyfman/cc-schema:2.0
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: loyalty-db-secret
