apiVersion: batch/v1
kind: Job
metadata:
  name: loyalty-database-load
  labels:
    app: loyalty-database-load
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: loyalty-database-load
          image: ykoyfman/schema-data:1.0-SNAPSHOT
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: loyalty-db-secret
