apiVersion: batch/v1
kind: Job
metadata:
  name: cc-schema-load
  labels:
    app: cc-schema-load
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: cc-schema-load
          image: ykoyfman/bank-schema-mesh:1.0
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: bank-db-secret
