apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-user-service
  labels:
    app: loyalty-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-user-service
  template:
    metadata:
      labels:
        app: loyalty-user-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: loyalty-user-service
        image: anthonyamanse/user-service:with-auth
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 9080
        envFrom:
        - secretRef:
            name: loyalty-db-secret
        - secretRef:
            name: loyalty-oidc-secret
---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-user-service
  labels:
    app: loyalty-user-service
spec:
  ports:
  - port: 9080
    targetPort: 9080
  selector:
    app: loyalty-user-service
